name: RVM tests

on: [push, pull_request]

jobs:
  build:
    name: Specs
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install apt packages
        run: sudo apt install -y gawk libgmp-dev
      - name: Run before_install commands
        run: |
          rm -f ~/.rvm/hooks/after_use
          sed -i'' -e '/rvm_project_rvmrc/d ; /rvm_silence_path_mismatch_check_flag/d' ~/.rvmrc || true
          echo rvm_show_log_lines_on_error=all >> ~/.rvmrc
          head -n 100 /etc/rvmrc ~/.rvmrc || true
          rvm list
          rvm use ruby-2.4 --fuzzy || rvm use ruby-2.3 --fuzzy
          [[ -n \"${LANG:-}\" ]] || export LANG=en_US.UTF-8
          env | grep '^rvm' || true
