name: RVM tests

on: [push, pull_request]

jobs:
  build:
    name: Specs
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Install apt packages
        run: apt install -y gawk libgmp-dev
