name: GPG signature
on: [push, pull_request]
jobs:
  build:
    name: GPG signature
    strategy:
      matrix:
        os: [ubuntu-latest]
        ruby: [2.7]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: GPG signature
        run: |
          sudo apt-get install -y gawk libgmp-dev dirmngr gnupg2
          gpg2 --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
          gpg2 --verify binscripts/rvm-installer.asc binscripts/rvm-installer

